import { AppTheme } from '../../types';

export const cyberLogic: AppTheme = {
  mode: 'dark',
  colors: {
    background: '#0B0E11',
    surface: '#111417',
    surfaceDim: '#111417',
    surfaceBright: '#37393d',
    surfaceContainerLowest: '#0b0e11',
    surfaceContainerLow: '#191c1f',
    surfaceContainer: '#1d2023',
    surfaceContainerHigh: '#272a2e',
    surfaceContainerHighest: '#323538',
    onSurface: '#e1e2e7',
    onSurfaceVariant: '#bbc9cf',
    inverseSurface: '#e1e2e7',
    inverseOnSurface: '#2e3134',
    outline: '#859399',
    outlineVariant: '#3c494e',
    surfaceTint: '#4cd6ff',
    primary: '#00D1FF',
    onPrimary: '#003543',
    primaryContainer: '#00d1ff',
    onPrimaryContainer: '#00566a',
    inversePrimary: '#00677f',
    secondary: '#2FF801',
    onSecondary: '#053900',
    secondaryContainer: '#2ff801',
    onSecondaryContainer: '#0f6d00',
    tertiary: '#FEB127',
    onTertiary: '#442b00',
    tertiaryContainer: '#feb127',
    onTertiaryContainer: '#6b4700',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
  },
  typography: {
    displayLg: {
      fontFamily: 'Inter',
      fontSize: 28,
      fontWeight: '700' as const,
      lineHeight: 34,
      letterSpacing: -0.02 * 28,
    },
    headlineMd: {
      fontFamily: 'Inter',
      fontSize: 20,
      fontWeight: '600' as const,
      lineHeight: 26,
      letterSpacing: -0.01 * 20,
    },
    titleLg: {
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '600' as const,
      lineHeight: 24,
    },
    titleMd: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '600' as const,
      lineHeight: 22,
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 24,
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    bodySm: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
    codeMd: {
      fontFamily: 'JetBrains Mono',
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    codeSm: {
      fontFamily: 'JetBrains Mono',
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
    labelCaps: {
      fontFamily: 'Space Grotesk',
      fontSize: 11,
      fontWeight: '600' as const,
      lineHeight: 14,
      letterSpacing: 0.55,
    },
    labelMd: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '500' as const,
      lineHeight: 20,
    },
    labelSm: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '500' as const,
      lineHeight: 16,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    gutter: 12,
    margin: 16,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  elevation: {
    level0: {
      backgroundColor: '#0B0E11',
    },
    level1: {
      backgroundColor: '#121212',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    level2: {
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.08)',
    },
  },
  glow: {
    primary: {
      shadowColor: '#00D1FF',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
    },
    secondary: {
      shadowColor: '#2FF801',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    error: {
      shadowColor: '#ffb4ab',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
  },
};
