import { AppTheme } from '../../types';

export const utilityMinimalist: AppTheme = {
  mode: 'light',
  colors: {
    background: '#f7f9ff',
    surface: '#f7f9ff',
    surfaceDim: '#d7dae1',
    surfaceBright: '#f7f9ff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f1f4fa',
    surfaceContainer: '#ebeef5',
    surfaceContainerHigh: '#e5e8ef',
    surfaceContainerHighest: '#e0e2e9',
    onSurface: '#181c21',
    onSurfaceVariant: '#424753',
    inverseSurface: '#2d3136',
    inverseOnSurface: '#eef1f8',
    outline: '#727785',
    outlineVariant: '#c2c6d6',
    surfaceTint: '#005bc0',
    primary: '#0051AE',
    onPrimary: '#ffffff',
    primaryContainer: '#0969da',
    onPrimaryContainer: '#ecefff',
    inversePrimary: '#adc6ff',
    secondary: '#565f69',
    onSecondary: '#ffffff',
    secondaryContainer: '#dae3ef',
    onSecondaryContainer: '#5c656f',
    tertiary: '#4d565d',
    onTertiary: '#ffffff',
    tertiaryContainer: '#656e76',
    onTertiaryContainer: '#e8f1fa',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
  },
  typography: {
    displayLg: {
      fontFamily: 'Inter',
      fontSize: 28,
      fontWeight: '700' as const,
      lineHeight: 34,
      letterSpacing: -0.02 * 28,
    },
    headlineMd: {
      fontFamily: 'Inter',
      fontSize: 20,
      fontWeight: '600' as const,
      lineHeight: 26,
      letterSpacing: -0.01 * 20,
    },
    titleLg: {
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '600' as const,
      lineHeight: 24,
    },
    titleMd: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '600' as const,
      lineHeight: 22,
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 24,
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    bodySm: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
    codeMd: {
      fontFamily: 'monospace',
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    codeSm: {
      fontFamily: 'monospace',
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
    labelCaps: {
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: '600' as const,
      lineHeight: 14,
      letterSpacing: 0.55,
    },
    labelMd: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '500' as const,
      lineHeight: 20,
    },
    labelSm: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '500' as const,
      lineHeight: 16,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    gutter: 16,
    margin: 16,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  elevation: {
    level0: {
      backgroundColor: '#f7f9ff',
    },
    level1: {
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#e0e2e9',
    },
    level2: {
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#c2c6d6',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
    },
  },
  glow: {
    primary: {},
    secondary: {},
    error: {},
  },
};
